### ISSUE TITLE
support upgrading major puppet versions

### ISSUE THREAD

**Issue by evgeni** [theforeman/foreman-operations-collection#20]
##### SUMMARY

Puppets `puppetX-release` RPMs (and probably Debs, untested) conflict with all other non-X versions (6 conflicts with 5, 7 with 6 and 6), but don't obsolete those. So just installing the new one while the old is installed doesn't work (yum transaction error). We need to remove the old version first.

In `forklift` we just have erased 5 when we installed 6: https://github.com/theforeman/forklift/blob/517d8ddcb77f6fb97525cb4efd35db5212c301fb/roles/puppet_repositories/tasks/puppetlabs-6-redhat.yml#L2-L7

To make it more generic here, I propose to define a list of supported versions (e.g `puppet_repositories_supported_versions: [6,7]`) and then have a task that erases all `puppetX-release` packages where X is in `{{ puppet_repositories_supported_versions | difference([puppet_repositories_version]) }}`.

##### ISSUE TYPE
 - Feature Idea

**Comment by ekohl** [comment]
Related upstream PR to solve this in the release files themselves: https://tickets.puppetlabs.com/browse/CPR-762.

**Comment by evgeni** [comment]
I remember seeing a similar ticket a long while ago, with no movement :(
