### ISSUE TITLE
installer role does not configure postgresql 12 module needed by katello 4.2 on centos8

### ISSUE THREAD

**Issue by RobVerduijn** [theforeman/foreman-operations-collection#45]
##### SUMMARY

According to the docs http://docs.theforeman.org katello 4.2 requires the postgresql 12 module on centos8
This is not enabled in the installer role (like the ruby2.7 module).

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```

```

##### COLLECTION VERSION

```

```

##### KATELLO/FOREMAN VERSION

```

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by Thulium-Drake** [comment]
I think I have addressed this in #43 :-)

**Comment by Thulium-Drake** [comment]
as also metioned by @evgeni in #43 this has been addressed in the foreman-installer. You only need to manually run the ```postgresql_upgrade``` role if you need to upgrade from 10 to 12.

**Comment by evgeni** [comment]
correct, the module doesn't need to be enabled manually
